my_homepage:
  path:     /
  defaults: { _controller: AppBundle:Default:index }

my_about:
  path:     /about/{name}
  defaults: { _controller: AppBundle:About:user, name:null}

my_about_more:
  path:     /about/{name}/details
  defaults: { _controller: AppBundle:About:details}