app_homepage:
  path:     /
  defaults: { _controller: AppBundle:Default:index }

app_about:
  path:     /about/{name}
  defaults: { _controller: AppBundle:About:user, name:null}

app_about_more:
  path:     /about/{name}/details
  defaults: { _controller: AppBundle:About:details}

workspace_show:
  path:     /workspace/{name}
  defaults: { _controller: AppBundle:Workspace:show, project:null}

